on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - jfkcooper:main
  workflow_dispatch:
  
name: CI
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pytest
         python -m pip install .
     - name: Test with pytest
       run: |
         python -m pytest 

  flake8-lint:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      # Install flake8 extensions (this step is not required. Default is "None").
      - name: Set up flake8
        run: pip install flake8-quotes flake8-docstrings
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
